### PR TITLE
Fix generation failing when the target type has at least one ctor with parameters

### LINKED ISSUE #30: Builder generation fails if the target type has at least one ctor with parameters
Due to the following check, an exception is thrown if the target DTO has at least one ctor with parameters, even if a parameterless one is available.

https://github.com/StefH/FluentBuilder/blob/main/src/FluentBuilderGenerator/FileGenerators/FluentBuilderClassesGenerator.cs#L247-L252 

The condition should be changed to
```csharp
classSymbol.NamedTypeSymbol.Constructors.IsEmpty || classSymbol.NamedTypeSymbol.Constructors.All(c => !c.Parameters.IsEmpty)
```

Writing out the thrown exception into the `Error.g.cs` file is great to allow errors to be analyzed - wouldn't it be good to also emit a compiler warning/error via `GeneratorExecutionContext.ReportDiagnostic(...)` for such an error? I think this would make the development experience even better.

Anyway, thank you for your work on this project!

### PR DESCRIPTION
**Pull request by iam-mholle**
Fixes #30

The test generating a builder for `DateTime` was actually incorrect, as `DateTime` does have a public parameterless ctor, thus the generation should succeed. I did remove the test, but if you want I can leave it in.

### CODE REVIEW

File: tests/FluentBuilderGeneratorTests/DTO/UserWithParameterizedConstructor.cs [hunk 1]
```diff
@@ -0,0 +1,26 @@
+﻿using System;
+
+namespace FluentBuilderGeneratorTests.DTO;
+
+public class UserWithParameterizedConstructor
```
Comment (StefH) [inline tests/FluentBuilderGeneratorTests/DTO/UserWithParameterizedConstructor.cs:5]: Can you rename this to `ThingWithParameterizedConstructor` ?

I want to use all `Thing***` classes for testing constructors.

**Review by StefH — CHANGES_REQUESTED** [review]

**Review by StefH — APPROVED** [review]
